#pragma once

#define BLUE_NOVEMBER_TAG		'BEEF'
#define BLUE_NOVEMBER_DEVICE	0x8000

#define BLUE_NOVEMBER_UNPROTECT_PROCESS			CTL_CODE(BLUE_NOVEMBER_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)
#define BLUE_NOVEMBER_PROTECT_PROCESS				CTL_CODE(BLUE_NOVEMBER_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)
#define BLUE_NOVEMBER_PROCESS_PRIVILEGE			CTL_CODE(BLUE_NOVEMBER_DEVICE, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)

#define BLUE_NOVEMBER_ENUM_PROCESS_CALLBACKS		CTL_CODE(BLUE_NOVEMBER_DEVICE, 0x810, METHOD_NEITHER, FILE_ANY_ACCESS)
#define BLUE_NOVEMBER_ZERO_PROCESS_CALLBACK		CTL_CODE(BLUE_NOVEMBER_DEVICE, 0x811, METHOD_NEITHER, FILE_ANY_ACCESS)
#define BLUE_NOVEMBER_ADD_PROCESS_CALLBACK		CTL_CODE(BLUE_NOVEMBER_DEVICE, 0x812, METHOD_NEITHER, FILE_ANY_ACCESS)

#define BLUE_NOVEMBER_ENUM_DSE					CTL_CODE(BLUE_NOVEMBER_DEVICE, 0x820, METHOD_NEITHER, FILE_ANY_ACCESS)
#define BLUE_NOVEMBER_DISABLE_DSE					CTL_CODE(BLUE_NOVEMBER_DEVICE, 0x821, METHOD_NEITHER, FILE_ANY_ACCESS)
#define BLUE_NOVEMBER_ENABLE_DSE					CTL_CODE(BLUE_NOVEMBER_DEVICE, 0x822, METHOD_NEITHER, FILE_ANY_ACCESS)